bot:
  token: "7741493113:AAFdZkaYWiY-LkNYeuKdx4TPjyUiaH7ij68"  # Replace with your real token
  chat_id: "@Farshid_cryptosignals"                        # Replace with your Telegram chat/channel ID
  symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - BNBUSDT
    - ADAUSDT
    - XRPUSDT
  interval: "1hour"
  monitoring_interval: 60

api:
  coinmarketcap:
    key: "f1c6dfa7-a427-4fd2-8b6b-a6f91b06e005"             # Replace with your real CoinMarketCap API key

logging:
  level: "INFO"
  format: "[%(asctime)s] %(levelname)s: %(message)s"
